version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.7
    steps:
      - checkout
      - run: npm install
      - run: npm run build:css && react-scripts build
      - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
        filters:
          branches:
            only: master
