version: 2
jobs:
  deploy_dev:
    docker:
      - image: circleci/node:10.7
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install --unsafe
      - run:
          name: build
          command: npm run build
      - run:
          name: deploy to Firebase Hosting
          command: ln -s ./node_modules/.bin/firebase . && ./firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  deploy_dev:
    jobs:
      - deploy_dev:
          filters:
            branches:
              only: master
